name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/linear-optimize/tex-builder:latest .
      
      - name: Run LaTeX compilation
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/local/workspace \
            ghcr.io/linear-optimize/tex-builder:latest \
            make all
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: master
          release_name: Release master
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
      - name: Upload Assets to Release with a wildcard
        uses: csexton/release-asset-action@v2
        with:
          pattern: "*.pdf"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}